document.writeln("<script>");
document.writeln("				function set_item_class(id){");
document.writeln("						for(i=1;i<=7;i++){");
document.writeln("							if(id==i){");
document.writeln("								document.getElementById(\"pro_\"+i+\"_2\").style.display=\"\";");
document.writeln("								document.getElementById(\"pro_\"+i+\"_2\").style.background=\"url(images/item_h\"+i+\"_on.jpg) no-repeat 10px 5px\";");
document.writeln("								document.getElementById(\"pro_\"+i+\"_1\").style.display=\"none\";");
document.writeln("							}else{");
document.writeln("								document.getElementById(\"pro_\"+i+\"_2\").style.display=\"none\";");
document.writeln("								document.getElementById(\"pro_\"+i+\"_1\").style.display=\"\";");
document.writeln("								document.getElementById(\"pro_\"+i+\"_1\").style.background=\"url(images/item_h\"+i+\".jpg) no-repeat 15px 4px\";");
document.writeln("							}");
document.writeln("						}");
document.writeln("					}");
document.writeln("				</script>");
document.writeln("            <div class=\"lbr3_c\">&nbsp;");
document.writeln("                <div class=\"autohei\">                        ");
document.writeln("                    <div id=\"h_item\" class=\"ch_jscont autohei\">");
document.writeln("                        <ul>");
document.writeln("                            <li onmouseover=\"set_item_class(1);\" id=\"pro_1_1\">");
document.writeln("                                <div class=\"jsbg\">");
document.writeln("                                    <p><span>炎症</span>德国O3蓝氧净疗术</p>");
document.writeln("                                </div>");
document.writeln("                            </li>");
document.writeln("                            <li style=\"display: none;\" id=\"pro_1_2\">");
document.writeln("                            	<div class=\"jsbg2\">");
document.writeln("                                    <p><span>炎症</span>德国O3蓝氧净疗术</p>");
document.writeln("                                </div>");
document.writeln("<a href=\"/xh/js/184.shtml\"><img src=\"/images/js_28.jpg\" width=\"267\" height=\"93\"></a>");
document.writeln("                            </li>");
document.writeln("                                ");
document.writeln("                            <li onmouseover=\"set_item_class(2);\" id=\"pro_2_1\" style=\" display: none;\">");
document.writeln("                                <div class=\"jsbg\">");
document.writeln("                                    <p><span>人流</span>she's无痛人流术</p>");
document.writeln("                                </div>");
document.writeln("                            </li>");
document.writeln("                            <li id=\"pro_2_2\">");
document.writeln("                            	<div class=\"jsbg2\">");
document.writeln("                                    <p><span>人流</span>she's无痛人流术</p>");
document.writeln("                                </div>");
document.writeln("<a href=\"/xh/js/195.shtml\"><img src=\"/images/js_27.jpg\" width=\"267\" height=\"93\"></a> ");
document.writeln("                            </li>");
document.writeln("                            ");
document.writeln("                            <li onmouseover=\"set_item_class(3);\" id=\"pro_3_1\" style=\" display: none;\">");
document.writeln("                                <div class=\"jsbg\">");
document.writeln("                                    <p><span>子宫</span>wolf宫腹腔镜微创术</p>");
document.writeln("                                </div>");
document.writeln("                            </li>");
document.writeln("                            <li id=\"pro_3_2\">");
document.writeln("                            	<div class=\"jsbg2\">");
document.writeln("                                    <p><span>子宫</span>wolf宫腹腔镜微创术</p>");
document.writeln("                                </div>");
document.writeln("<a href=\"/xh/js/190.shtml\"><img src=\"/images/js_22.jpg\" width=\"267\" height=\"93\"></a>");
document.writeln("                            </li>");
document.writeln("                            ");
document.writeln("                            <li onmouseover=\"set_item_class(4);\" id=\"pro_4_1\" style=\" display: none;\">");
document.writeln("                                <div class=\"jsbg\">");
document.writeln("                                    <p><span>宫颈</span>第五代LEEP刀技术</p>");
document.writeln("                                </div>");
document.writeln("                            </li>");
document.writeln("                            <li id=\"pro_4_2\">");
document.writeln("                            	<div class=\"jsbg2\">");
document.writeln("                                    <p><span>宫颈</span>第五代LEEP刀技术</p>");
document.writeln("                                </div>");
document.writeln("<a href=\"/xh/js/191.shtml\"><img src=\"/images/js_23.jpg\" width=\"267\" height=\"93\"></a>");
document.writeln("                            </li>");
document.writeln("                            ");
document.writeln("                            <li onmouseover=\"set_item_class(5);\" id=\"pro_5_1\" style=\" display: none;\">");
document.writeln("                                <div class=\"jsbg\">");
document.writeln("                                    <p><span>月经</span>中西结合平衡疗法</p>");
document.writeln("                                </div>");
document.writeln("                            </li>");
document.writeln("                            <li id=\"pro_5_2\">");
document.writeln("                            	<div class=\"jsbg2\">");
document.writeln("                                    <p><span>月经</span>中西结合平衡疗法</p>");
document.writeln("                                </div>");
document.writeln("<a href=\"/xh/js/188.shtml\"><img src=\"/images/js_24.jpg\" width=\"267\" height=\"93\"></a>");
document.writeln("                            </li>");
document.writeln("                            ");
document.writeln("                            <li onmouseover=\"set_item_class(6);\" id=\"pro_6_1\" style=\" display: none;\">");
document.writeln("                                <div class=\"jsbg\">");
document.writeln("                                    <p><span>不孕</span>三镜一丝输卵管疏通术</p>");
document.writeln("                                </div>");
document.writeln("                            </li>");
document.writeln("                            <li id=\"pro_6_2\">");
document.writeln("                            	<div class=\"jsbg2\">");
document.writeln("                                    <p><span>不孕</span>三镜一丝输卵管疏通术</p>");
document.writeln("                                </div>");
document.writeln("<a href=\"/xh/js/180.shtml\"><img src=\"/images/js_26.jpg\" width=\"267\" height=\"93\"></a>");
document.writeln("                            </li>");
document.writeln("                           ");
document.writeln("                        </ul>");
document.writeln("                        <script>set_item_class(1);</script>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");