// @by guihua_liu
// 2015-8-27


//单选按钮效果
;
(function(){
	'use strict';
	//创建单选按钮的弹窗div
	function createDiv(){
		var i=0;
		i++;
		//创建div
		window.oDiv=document.createElement('div'+i);
		oDiv.id='myDiv';
		oDiv.innerHTML='<div class="radio_wrap">'
                            	+'<form class="form-horizontal">'
                                        +'<div class="form-group">'
                                          +' <label for="" class="col-sm-2 control-label">问题标题</label>'
                                              +' <div class="col-sm-9 jq_tit">'
                                                       +' <input type="text" class="form-control jq_title"  id="title_value" onmouseover="jqtitleover()" onmouseout="jqtitleout()" placeholder="输入问题标题">'
													   +'<div class="btn-group btn_hover" onmouseover="jqtitleover()" onmouseout="jqtitleout()">'
															  +'<button type="button" class="btn_img">'
																+' <span class="glyphicon glyphicon-picture"></span>'
															  +'</button>'
															  +'<button type="button" class="btn_img btn_imgl" data-toggle="modal" data-target="#myModal" onclick="modalframe()">'
																 +'<span class="glyphicon glyphicon-text-size"></span>'
															  +'</button>'
														+'</div>'
														+'<div class="dropdown btn_hover btn_down" onmouseover="jqtitleover()" onmouseout="jqtitleout()">'
														
															  +'<button class="btn btn-default dropdown-toggle btn_img" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">'
																+'<span class="glyphicon glyphicon-info-sign" onmouseover="tipsover()" onmouseout="tipsout()">'	
																+'</span>'+'<span>引用...</span>'+'<span class="caret"></span>'
																+'<div class="popover left pop_left">'
																																+'<div class="arrow"></div>'
																	+'<h3 class="popover-title">引用</h3>'
																	+'<div class="popover-content">'
																	+'<p>通过“引用”可以将答题者之前所回答问题的答案作为标签插入到问题标签或选项中。</p>'
																	+'<p>只需点击“引用...”按钮，您就可以在弹出的问题列表中选择想要引用的答案。</p>'
																	+'<p>注意：您只能引用在之前的页面中出现过的问题。建议您在问卷的整个结构完成以后再调整使用功能，使用引用后再调整问题的顺序可能导致引用失效。</p>'
 +'</div>'

  +'</button>'
  
  +'<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">'
    +'<li><a href="#">Q1.你喜欢什么口味的冰淇淋?</a></li>'
    +'<li><a href="#">Q2.问题2</a></li>'
    +'<li><a href="#">Q3.问题3</a></li>'
  +'</ul>'
															 
														+'</div>'
                                                +'</div>'
                                                 
                                        +'</div>'
                                        +'<div class="form-group">'
                                          +' <label for="" class="col-sm-2 control-label">选项和设置</label>'
                                               +' <div class="col-sm-1">'
                                                    +' <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>' 
                                               +' </div>'
                                                +'<div class="col-sm-2">'
                                                  +'  <select class="form-control select-stace">'
                                                    +'<option>单选题</option>'
                                                      +' <option value="1">多选题</option>'
                                                       +'<option value="2">填空题</option>'
                                                      +' <option value="3">多项填空题</option>'
                                                      +'<option value="4">评分题</option>'
                                                       +'<option value="5">排序题</option>'
                                                       +'<option value="6">文件上传题</option>' 
                                                       +'<option value="7">矩阵题</option>'
                                                       +'<option value="8">图片题</option>'
                                                       +'<option value="9">描述说明</option>'
                                                       +'<option value="10">插入分页</option>'   
                                                   +'</select>'
                                               +'</div>'
                                               +'<div class="btn-group btn_right">'
                                                    +'<button class="btn btn-primary" type="button" id="bd_active" onclick="nsanswer()">该题必答'
                                                    +'</button>'
                                               +'</div>'
                                               +'<div class="btn-group">'
                                                    +'<button class="btn btn-default " id="sj_active" onclick="randombtn()" type="button">选项随机'
                                                     +'</button>'
                                               +'</div>'                                             
                                       +'</div>'
                                       +'<ul class="radio_ul">'
                                          +'<li class="form-group" id="radio_con">'
                                                  +'<div class="col-sm-10 col-sm-offset-2">'
                                                        +'<div class="col-sm-1">'
                                                                +'<input type="radio" class="form-control" id="">'
                                                        +'</div>'
                                                       +'<div class="col-sm-8 jq_tit">'
                                                              +'<input type="text" class="form-control jq_title" id="change_one"  onmouseover="jqtitleoverone()" onmouseout="jqtitleoutone()" placeholder="选项">'
															  +'<div class="btn-group btn_over" onmouseover="jqtitleoverone()" onmouseout="jqtitleoutone()">'
															  +'<button type="button" class="btn_img">'
																+' <span class="glyphicon glyphicon-picture"></span>'
															  +'</button>'
															  +'<button type="button" class="btn_img btn_imgl" data-toggle="modal" data-target="#myModal" onclick="modalframe()">'
																 +'<span class="glyphicon glyphicon-text-size"></span>'
															  +'</button>'
														+'</div>'
														+'<div class="dropdown btn_over btn_down" onmouseover="jqtitleoverone()" onmouseout="jqtitleoutone()">'
														
															  +'<button class="btn btn-default dropdown-toggle btn_img" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">'
																+'<span class="glyphicon glyphicon-info-sign" onmouseover="tipsoverone()" onmouseout="tipsoutone()">'	
																+'</span>'+'<span>引用...</span>'+'<span class="caret"></span>'
																+'<div class="popover left pop_lefts" id="tips_div">'
																																+'<div class="arrow"></div>'
																	+'<h3 class="popover-title">引用</h3>'
																	+'<div class="popover-content">'
																	+'<p>通过“引用”可以将答题者之前所回答问题的答案作为标签插入到问题标签或选项中。</p>'
																	+'<p>只需点击“引用...”按钮，您就可以在弹出的问题列表中选择想要引用的答案。</p>'
																	+'<p>注意：您只能引用在之前的页面中出现过的问题。建议您在问卷的整个结构完成以后再调整使用功能，使用引用后再调整问题的顺序可能导致引用失效。</p>'
 +'</div>'

  +'</button>'
  
  +'<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">'
    +'<li><a href="#">Q1.你喜欢什么口味的冰淇淋?</a></li>'
    +'<li><a href="#">Q2.问题2</a></li>'
    +'<li><a href="#">Q3.问题3</a></li>'
  +'</ul>'
															 
														        +'</div>'
                                                
                                                          +'</div>'
                                                        +'<div class="col-sm-1" >'
                                                               +'<button type="button" class="close" onclick="closebtn(this)" aria-label="Close">'
                                                               +'<span aria-hidden="true">&times;</span>'
                                                               +'</button>'
                                                         +'</div>'
                                                   +'</div>'
                                           +'</li>'
                                           +'<li class="form-group clone">'
                                                  +'<div class="col-sm-10 col-sm-offset-2">'
                                                         +'<div class="col-sm-1">'
                                                               +'<input type="radio" class="form-control">'
                                                         +'</div>'
                                                         +'<div class="col-sm-8">'
                                                               +'<input type="text" class="form-control" id="change_two" onmouseover="jqtitleovertwo()" onmouseout="jqtitleouttwo()" placeholder="选项">'
															   +'<div class="btn-group btn_hovers" onmouseover="jqtitleovertwo()" onmouseout="jqtitleouttwo()">'
															  +'<button type="button" class="btn_img">'
																+' <span class="glyphicon glyphicon-picture"></span>'
															  +'</button>'
															  +'<button type="button" class="btn_img btn_imgl" data-toggle="modal" data-target="#myModal" onclick="modalframe()">'
																 +'<span class="glyphicon glyphicon-text-size"></span>'
															  +'</button>'
														+'</div>'
														+'<div class="dropdown btn_hovers btn_down" onmouseover="jqtitleovertwo()" onmouseout="jqtitleouttwo()">'
														
															  +'<button class="btn btn-default dropdown-toggle btn_img" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">'
																+'<span class="glyphicon glyphicon-info-sign" onmouseover="tipsovertwo()" onmouseout="tipsouttwo()">'	
																+'</span>'+'<span>引用...</span>'+'<span class="caret"></span>'
																+'<div class="popover left pop_leftr">'
																																+'<div class="arrow"></div>'
																	+'<h3 class="popover-title">引用</h3>'
																	+'<div class="popover-content">'
																	+'<p>通过“引用”可以将答题者之前所回答问题的答案作为标签插入到问题标签或选项中。</p>'
																	+'<p>只需点击“引用...”按钮，您就可以在弹出的问题列表中选择想要引用的答案。</p>'
																	+'<p>注意：您只能引用在之前的页面中出现过的问题。建议您在问卷的整个结构完成以后再调整使用功能，使用引用后再调整问题的顺序可能导致引用失效。</p>'
 +'</div>'

  +'</button>'
  
  +'<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">'
    +'<li><a href="#">Q1.你喜欢什么口味的冰淇淋?</a></li>'
    +'<li><a href="#">Q2.问题2</a></li>'
    +'<li><a href="#">Q3.问题3</a></li>'
  +'</ul>'
															 
																+'</div>'
                                                          +'</div>'
                                                        +'<div class="col-sm-1">'
                                                              +'<button type="button" class="close" onclick="closebtn(this)" aria-label="Close">'
                                                               +'<span aria-hidden="true">&times;</span>'
                                                               +'</button>'
                                                         +'</div>'
                                                   +'</div>'
                                           +'</li>'
    									+'<li class="form-group">'
                                                   +'<div class="col-sm-9 col-sm-offset-2">'
															+'<div class="col-sm-9 col-sm-offset-1">'
																+'<input type="text" class="form-control new_btn"  id="new_btn" onclick="copybtn()" placeholder="新建选项">'
                                                                 +'</div>'
												+'</div>'
                                            +'</li>'
  											+'<li class="form-group">'
                                                    +'<div class="col-sm-4 col-sm-offset-3">'
																 +'<a href="javascript:;">添加[其他]选项</a> | <a href="javascript:;">批量添加</a>'
                                                                 
													+'</div>'
                                            +'</li>'

                                        +'</ul>'
                                        +'<div class="form-group">'
                                        	+'	<div class="col-sm-9 col-sm-offset-2 splite_div" id="splite_div">'
                                              +'<div class="col-sm-1">'
                                                                +'<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>'  
                                                        +'</div>'
                                                        +'<div class="col-sm-3">'
														+'<span>每行显示</span>'
														+'<select class="select-stace">'
                                                                +'<option selected="selected" value="0">1</option>'
                                                                +'<option value="1">2</option>'
                                                                +'<option value="2">3</option>'
                                                                +'<option value="3">4</option>'
                                                                +'<option value="4">5</option>'
                                                                +'<option value="5">6</option>'
                                                                +'<option value="6">7</option>'
                                                                +'<option value="7">8</option>'
                                                                +'<option value="8">9</option>'
                                                                +'<option value="9">10</option>'  
                                                            +'</select>'
                                                            +'<span>列</span>'
                                                        +'</div>'
                                                        +'<a href="javascript:;"><span class="glyphicon glyphicon-random" aria-hidden="true"></span> 逻辑设置</a>'
                                                +'</div>'
                                                +'<div class="col-sm-9 col-sm-offset-2 row_split">'
                                                	+' <div class="split"></div>'
                                                     +'<a href="javascript:;" class="adv_setting" onclick="advsetting()">'
                                                        +'<span>展开高级设置</span>' 
                                                         +'<span class="caret" id="caret"></span>'
                                                     +'</a>'
                                                +'</div>'
                                        +'</div>'
                                        +'<div class="form-group">'
                                        	+'<div class="col-sm-3 col-sm-offset-5">'
                                            	+'<button type="button" class="btn btn-primary btn_right" id="confirm_btn" onclick="confirmbtn()">确定</button>'
                                                +'<button type="button" class="btn btn-default can_cur" id="cancel_btn" onclick="closediv()">取消</button>'
                                           +'</div>'
                                        +'</div>'
                                 +'</form>'
                            +'</div>';
	};
	//给页面添加创建的div
	$('#radio').click(function(){
			createDiv();
			$('#radio_wrap').append(oDiv);
	});
					
	
})()
;

